### ISSUE TITLE
what's the arg means? /Applications/Unity/Unity.app/Contents/Tools

### ISSUE THREAD

**Issue by nopa607** [faelenor/asset-bundle-analyzer#15]
always ,i use unity in windows to pack the assets into a assetBundle,
but, i cann't understand why the unity tool folder is needed in this project?
what should it be in windows PC?

**Comment by shelllee** [comment]
1. this tool need some unity tools such as `WebExtract`

1. windows dir:

    `your_unity_install_dir\Editor\Data\Tools`:

    `"C:\Program Files\Unity\2020117f1\Editor\Data\Tools"` for example.
