### ISSUE TITLE
Warning: unhandled type Type*!

### ISSUE THREAD

**Issue by litefeel** [faelenor/asset-bundle-analyzer#4]
Hi.
I used this tool and it is very useful.
When I analyze the asset bundle, it displays `Warning: unhandled type Type*!`.
What is `Type*`?
Thanks.

**Comment by faelenor** [comment]
The tool can handle most of the types used internally by Unity, but some are not recognized and when it happens, this warning is issued. It doesn't really break anything, but the size of the asset may be a little bit off. The size an approximation anyway. I should probably rework this a bit and remove the warning as it is more confusing than helping.
