### ISSUE TITLE
How to export the information from player like asset bundle.

### ISSUE THREAD

**Issue by litefeel** [faelenor/asset-bundle-analyzer#6]
Hi.
Thank you for the tool.
This is very useful for analyzing resources and optimizing resources.

Now. How to analyze the resources built into the player.
How to export the information from player like asset bundle.
Thanks.

![image](https://user-images.githubusercontent.com/1288575/80268846-4ca50900-86dd-11ea-861e-6b64ef1018b0.png)

**Comment by faelenor** [comment]
Hi,
Unfortunately, there is no tool to extract the content of player data (WebExtract/binary2text don't work with it). As workaround, you can put all your data in asset bundles. Having everything in asset bundles is usually a best practice as well.

**Comment by litefeel** [comment]
Thanks.
