### ISSUE TITLE
'args' not defined

### ISSUE THREAD

**Issue by ReaperUnreal** [faelenor/asset-bundle-analyzer#7]
When running the latest version on macOS 10.14 I'm getting this error:
`-> python3 analyzer.py /Applications/Unity/Hub/Editor/2019.3.0f6/Unity.app/Contents/Tools ~/work/sizes/validation1-bundles/
Traceback (most recent call last):
  File "analyzer.py", line 1450, in <module>
    main()
  File "analyzer.py", line 52, in main
    run_tool_with_timeout("WebExtract", filepath, ret_code, 60, 0)
  File "analyzer.py", line 1416, in run_tool_with_timeout
    p = Process(run_tool(tool, filepath, ret_code, level))
  File "analyzer.py", line 1432, in run_tool
    path = os.path.join(args.tool_path, tool)
NameError: name 'args' is not defined`

This happens with both python 2 and 3.
When I roll back to the previous commit on github everything works as expected on python 2. I think something might've gone wrong in the python 3 conversion.

**Comment by faelenor** [comment]
Thanks for reporting this. It was fixed in the last commit. I have no idea how that change ended up there!
